### ISSUE TITLE
Panic when attempting to use Backtab

### ISSUE THREAD

**Issue by spacez320** [mum4k/termdash#360]
Pressing the 'backtab' key (a.k.a. Shift + Tab) throws an error in Termdash.

```
panic: unknown keyboard key '278' in a keyboard event Backtab
goroutine 31 [running]:
  internal/lib.errorTermdashHandler({0x95a4c0?, 0xc0016f5af0})
    /home/matthew/workspace/personal/cryptarch/internal/lib/display_termdash.go:59 +0x75
  github.com/mum4k/termdash.(*termdash).handleError(...)
    /home/matthew/lib/go/pkg/mod/github.com/mum4k/termdash@v0.18.0/termdash.go:250
  github.com/mum4k/termdash.(*termdash).subscribers.func1({0x95a660?, 0xc0016f5ad0?})
    /home/matthew/lib/go/pkg/mod/github.com/mum4k/termdash@v0.18.0/termdash.go:215 +0xbc
  github.com/mum4k/termdash/private/event.(*subscriber).callback(0xc00033e200, {0x95a660?, 0xc0016f5ad0?})
    /home/matthew/lib/go/pkg/mod/github.com/mum4k/termdash@v0.18.0/private/event/event.go:95 +0x31
  github.com/mum4k/termdash/private/event.(*subscriber).run(0xc00033e200, {0x95d8f0, 0xc0000940a0})
    /home/matthew/lib/go/pkg/mod/github.com/mum4k/termdash@v0.18.0/private/event/event.go:110 +0x5a
  created by github.com/mum4k/termdash/private/event.newSubscriber
    /home/matthew/lib/go/pkg/mod/github.com/mum4k/termdash@v0.18.0/private/event/event.go:89 +0x28d
```

This is a supported key in Tcell, at least. https://godocs.io/github.com/gdamore/tcell/v2#Key

Currently I have my program throwing away the error with a handler, but would be nice to properly support the key press.

**Comment by spacez320** [comment]
@mum4k Thanks for the response. I'd be happy to contribute this. Let me know if there's a time table, but otherwise should be able to report back soon.

**Comment by mum4k** [comment]
Thank you @spacez320, no rush - I don't keep any regular release schedule for Termdash. We can tag a new version once we have your PR in.

Thank you for your help!

**Comment by spacez320** [comment]
Thanks @mum4k . I have a PR here: https://github.com/mum4k/termdash/pull/362, let me know how it looks.
